version: '3'
services:
  api:
    build: ./api
    ports:
      - 3000:3000
    volumes:
      - ./api:/api
    depends_on:
      - mongo
  web-app:
    build: ./web-app
    ports:
      - 4200:4200
    volumes:
      - ./web-app:/web-app
    depends_on:
      - api
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
