version: '3'
services:
  api:
    build: ./api
    ports:
      - 3000:3000
    depends_on:
      - mongo
  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    ports:
      - 3080:3080
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
